name: CI
on:
  schedule:
    # Run this once a week
    - cron: '0 0 * * 0'

jobs:
  update-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:neovim-ppa/unstable
          sudo apt-get -y update
          sudo apt-get -y install doxygen luajit neovim python3-msgpack
      - name: Clone Neovim's repo and run gen_vimdoc.py
        run: |
          git clone --depth=1 https://github.com/neovim/neovim.git /tmp/neovim-repo
          cd /tmp/neovim-repo
          python3 ./scripts/gen_vimdoc.py
      - uses: actions/checkout@v3
      - name: Generate new docs
        run: |
          cp /tmp/neovim-repo/runtime/doc/*.mpack ./data/
          nvim --headless -c "luafile ./lua/lua-dev/parser.lua" -c "q"
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update api docs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
